### PR TITLE
docs: Add rule 5

### PR DESCRIPTION
**Pull request by Mangrove-Sun**
docs: Add rule 5

### CODE REVIEW

**Comment by Tchaikovsky1114** [comment]
please write your name

**Review by Tchaikovsky1114 — CHANGES_REQUESTED** [review]
please write your massege

**Comment by Tchaikovsky1114** [comment]
please write your massege

**Comment by Mangrove-Sun** [comment]
OK

**Review by Tchaikovsky1114 — CHANGES_REQUESTED** [review]
please rewrite code

**Pull request merged**
